# $ sudo docker-compose build
# $ sudo docker-compose up
# $ sudo docker-compose run web <command>

version: "3.3"

services:
  db:
    image: postgres:12
    hostname: db
    environment:
        POSTGRES_DB: feeder_local_db
        POSTGRES_PASSWORD: example
    volumes:
      - ./ci/db:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - feeder

  web:
    build: .
    env_file:
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - feeder

  redis:
    image: redis:alpine
    ports:
    - "6379:6379"
    networks:
      - feeder

  celery:
    build: .
    command: celery -A feeder.celery worker -B -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    networks:
      - feeder

networks:
    feeder:
      external: true
