# $ sudo docker-compose build
# $ sudo docker-compose up
# $ sudo docker-compose run app <command>

version: "3.3"

# TODO: Нужно пофиксить docker-compose, но сначала стоит интегрировать poetry

services:
  db:
    image: postgres:12
    volumes:
      - ./ci/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata/
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=feeder_user
      - POSTGRES_PASSWORD=feeder_pwd
      - POSTGRES_DB=feeder_db
    networks:
      - feeder_local

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - feeder_local

  celery:
    build: .
    command: celery -A feeder.celery worker -B -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    links:
      - redis
    depends_on:
      - db
      - redis
    networks:
      - feeder_local

  app:
    build: ./
    command: bash -c "python manage.py migrate && uvicorn feeder.asgi:application --workers 2 --host 0.0.0.0 --port 9000 --reload"
    volumes:
      - ./ci/db:/var/lib/app/data
    depends_on:
      - db
      - redis
      - celery
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - feeder_local

networks:
    feeder_local:
