# $ sudo docker-compose build
# $ sudo docker-compose up
# $ sudo docker-compose run web <command>

version: "3.3"

services:
  db:
    image: postgres:12
    hostname: db
    environment:
        POSTGRES_DB: feeder_local_db
        POSTGRES_PASSWORD: example
    volumes:
      - ./ci/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - feeder_local

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - feeder_local

  celery:
    build: .
    command: celery -A feeder.celery worker -B -l info
    volumes:
      - .:/code
    env_file:
      - ./.env
    links:
      - redis
    depends_on:
      - db
      - redis
    networks:
      - feeder_local

networks:
    feeder_local:
      external: true