# Generated by Django 4.0.3 on 2022-03-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spotify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='albumnotification',
            name='discarded_by',
            field=models.ManyToManyField(blank=True, related_name='discarded_album_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отказавшиеся от уведомления'),
        ),
        migrations.AddField(
            model_name='albumnotification',
            name='received_by',
            field=models.ManyToManyField(blank=True, related_name='received_album_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist'),
        ),
    ]
