# Generated by Django 3.1.5 on 2021-05-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0004_albumnotification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="albumnotification",
            old_name="users",
            new_name="subscribers",
        ),
    ]
