# Generated by Django 3.1.5 on 2021-05-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0005_auto_20210505_2046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="albumnotification",
            name="release_date",
        ),
    ]
