# Generated by Django 3.1.5 on 2021-05-11 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_remove_albumnotification_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumnotification',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
