# Generated by Django 3.1.5 on 2021-05-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_auto_20210513_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumnotification',
            options={'ordering': ['-created_datetime'], 'verbose_name_plural': 'Оповещения об альбомах'},
        ),
    ]
