# Generated by Django 4.0.3 on 2022-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_committed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artist subscription',
                'verbose_name_plural': 'Artist subscriptions',
            },
        ),
        migrations.CreateModel(
            name='ChannelSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_committed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Channel subscription',
                'verbose_name_plural': 'Channel subscription',
            },
        ),
    ]
