# Generated by Django 4.0.3 on 2022-03-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0001_initial'),
        ('subscription', '0001_initial'),
        ('spotify', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsubscription',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='youtube.channel'),
        ),
        migrations.AddField(
            model_name='channelsubscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistsubscription',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='spotify.artist'),
        ),
        migrations.AddField(
            model_name='artistsubscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='channelsubscription',
            unique_together={('channel', 'subscriber')},
        ),
        migrations.AlterUniqueTogether(
            name='artistsubscription',
            unique_together={('artist', 'subscriber')},
        ),
    ]
