# Generated by Django 3.1.5 on 2021-05-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0004_albumnotification"),
        ("subscription", "0005_auto_20210505_2021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistsubscription",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="spotify.artist",
            ),
        ),
    ]
