# Generated by Django 3.1.4 on 2020-12-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtuber',
            new_name='author',
        ),
    ]
