# Generated by Django 3.1.4 on 2020-12-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20201217_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='author',
            new_name='youtuber',
        ),
    ]
