# Generated by Django 3.1.4 on 2020-12-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201218_1628'),
        ('youtube', '0003_auto_20201217_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Youtuber',
            new_name='Channel',
        ),
    ]
