# Generated by Django 3.1.4 on 2020-12-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_auto_20201222_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtuber',
            new_name='channel',
        ),
    ]
