# Generated by Django 3.1.4 on 2020-12-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20201217_1921'),
        ('user', '0002_auto_20201203_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_youtubers',
            field=models.ManyToManyField(related_name='followed_youtubers', to='youtube.Youtuber'),
        ),
    ]
