# Generated by Django 3.1.4 on 2020-12-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20201217_1940'),
        ('user', '0003_user_followed_youtubers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followed_youtubers',
            field=models.ManyToManyField(related_name='following_users', to='youtube.Youtuber'),
        ),
    ]
