# Generated by Django 3.1.4 on 2020-12-22 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201218_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followed_youtubers',
            new_name='followed_channels',
        ),
    ]
