# Generated by Django 3.1.4 on 2021-01-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201222_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_artists',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followed_channels',
        ),
    ]
