# Generated by Django 3.1.4 on 2021-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0007_videonotification'),
        ('spotify', '0015_albumnotification'),
        ('user', '0006_auto_20210105_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artist_subscriptions',
            field=models.ManyToManyField(to='spotify.AlbumNotification'),
        ),
        migrations.AddField(
            model_name='user',
            name='channel_subscriptions',
            field=models.ManyToManyField(to='youtube.VideoNotification'),
        ),
    ]
