# Generated by Django 3.1.4 on 2021-01-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210112_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='artist_subscriptions',
        ),
        migrations.RemoveField(
            model_name='user',
            name='channel_subscriptions',
        ),
    ]
