# Generated by Django 3.1.4 on 2021-01-17 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtube', '0001_initial'),
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video')),
            ],
            options={
                'ordering': ['-creation_datetime'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
            ],
            options={
                'ordering': ['-creation_datetime'],
                'abstract': False,
            },
        ),
    ]
