# Generated by Django 3.1.4 on 2020-12-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content_pk',
            new_name='object_id',
        ),
    ]
