# Generated by Django 3.1.4 on 2020-12-16 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20201216_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-creation_date_time']},
        ),
        migrations.AddField(
            model_name='notification',
            name='creation_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
