# Generated by Django 3.1.4 on 2021-01-17 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0001_initial'),
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsubscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artistsubscription',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist'),
        ),
        migrations.AddField(
            model_name='artistsubscription',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
