# Generated by Django 3.1.4 on 2021-01-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210105_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='author_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='author_id',
            new_name='object_id',
        ),
    ]
