# Generated by Django 3.1.4 on 2021-01-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20210107_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
