# Generated by Django 4.0.3 on 2022-03-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('youtube_id', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('youtube_id', models.CharField(max_length=256, unique=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='video_covers')),
                ('release_datetime', models.DateTimeField()),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtube.channel')),
            ],
            options={
                'ordering': ['-release_datetime'],
            },
        ),
        migrations.CreateModel(
            name='VideoNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('discarded_by', models.ManyToManyField(blank=True, related_name='discard_video_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатели, отказавшиеся от уведомления')),
                ('received_by', models.ManyToManyField(blank=True, related_name='received_video_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатели')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name_plural': 'Оповещения о видео',
                'ordering': ['-created_datetime'],
            },
        ),
    ]
