# Generated by Django 3.1.5 on 2021-05-05 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0002_videonotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videonotification',
            name='users',
        ),
        migrations.AddField(
            model_name='videonotification',
            name='subscribers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
