# Generated by Django 3.1.5 on 2021-05-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0003_auto_20210505_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videonotification',
            old_name='release_date',
            new_name='release_datetime',
        ),
    ]
