# Generated by Django 3.1.5 on 2021-05-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_auto_20210507_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='release_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
