# Generated by Django 3.1.5 on 2021-05-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0005_auto_20210509_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='release_datetime',
            field=models.DateTimeField(),
        ),
    ]
