# Generated by Django 3.1.5 on 2021-05-11 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("youtube", "0007_remove_videonotification_release_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videonotification",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Подписчики"
            ),
        ),
    ]
