# Generated by Django 3.1.5 on 2021-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtube", "0010_videonotification_created_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videonotification",
            name="created_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
