# Generated by Django 3.1.5 on 2021-05-12 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0011_auto_20210511_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonotification',
            name='to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
    ]
