# Generated by Django 3.1.5 on 2021-05-13 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube', '0012_videonotification_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videonotification',
            name='to',
        ),
        migrations.AddField(
            model_name='videonotification',
            name='discarded_by',
            field=models.ManyToManyField(blank=True, related_name='discard_video_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатели, отказавшиеся от уведомления'),
        ),
        migrations.AddField(
            model_name='videonotification',
            name='received_by',
            field=models.ManyToManyField(blank=True, related_name='received_video_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
    ]
