# Generated by Django 3.1.4 on 2020-12-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20201206_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='spotify_url',
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
