# Generated by Django 3.1.4 on 2020-12-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_remove_artist_spotify_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spotify.artist'),
        ),
    ]
