# Generated by Django 3.1.4 on 2020-12-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_auto_20201211_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('album', 'album'), ('single', 'single')], default='album', max_length=6),
            preserve_default=False,
        ),
    ]
