# Generated by Django 3.1.4 on 2020-12-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_auto_20201212_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
