# Generated by Django 3.1.4 on 2020-12-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_auto_20201217_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
    ]
