# Generated by Django 3.1.4 on 2021-01-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0012_remove_artist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
