# Generated by Django 3.1.4 on 2021-01-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0014_auto_20210108_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.album')),
            ],
            options={
                'ordering': ['-creation_time'],
                'abstract': False,
            },
        ),
    ]
